Improve handling with CAS for future
home-assistant/supervisor pull request #3506
Opened 2022-03-10 12:47 UTC by pvizeli

This reverts commit 435241bccf3f3c678161b50cfefd4b036f1daba9.

## Proposed change

Reduce requests and handling error case better without making a backlog

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] Local tests pass. **Your PR cannot be merged unless tests pass**
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] The code has been formatted using Black (`black --fast supervisor tests`)
- [ ] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

2022-03-23 15:01 UTC, pvizeli commented on supervisor/resolution/checks/core_trust.py
>              pass
I don't have an opinion on that, but we can general send errors on sys_security to sentry if you would like it

2022-03-29 17:23 UTC, mdegat01 requested changes
Looks like there's some commented out code. Good to go otherwise.

2022-03-29 17:24 UTC, mdegat01 commented on supervisor/resolution/checks/core_trust.py
>              pass
Yea I feel like that would help us keep ahead of this. I can do it as a separate PR though.

2022-03-30 12:16 UTC, pvizeli commented
> Looks like there's some commented out code. Good to go otherwise.

yeah, we going step by step

2022-03-31 14:59 UTC, mdegat01 approved these changes

2022-03-31 14:59 UTC, merged