addons/info returns info on all addons
home-assistant/supervisor pull request #3762
Opened 2022-08-01 22:22 UTC by mdegat01

## Proposed change

Allow `/addons/{slug}/info` to return info on all addons (installed or not) as it used to so we don't break ZwaveJS in older versions of HA.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to the supervisor)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:
- Link to cli pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] The code has been formatted using Black (`black --fast supervisor tests`)
- [x] Tests have been added to verify that the new code works.

If API endpoints of add-on configuration are added/changed:

- [ ] Documentation added/updated for [developers.home-assistant.io][docs-repository]

[dev-checklist]: https://developers.home-assistant.io/docs/en/development_checklist.html
[docs-repository]: https://github.com/home-assistant/developers.home-assistant

2022-08-02 07:16 UTC, pvizeli requested changes
Please only use the legacy path

2022-08-02 22:36 UTC, mdegat01 commented
@pvizeli I wasn't sure on the optimal approach here. It didn't seem like aiohttp middleware were designed for changing the handler. Plus that would add a small amount of overhead to all API calls to handle this problem with one API. I choose instead to add a wrapper to the info route to handle legacy routing in case of a particular exception. If you have an alternate suggestion let me know.

2022-08-03 10:08 UTC, pvizeli commented on .vscode/launch.json
> +      ]
?

2022-08-03 10:08 UTC, pvizeli approved these changes

2022-08-03 13:44 UTC, merged